apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "34.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
    service:
      type: ClusterIP
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.local`)
        entryPoints: ["web"]
