apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-victorialogs
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  victorialogs.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        url: http://victoria-logs-server.monitoring.svc.cluster.local:9428
        access: proxy
        isDefault: false
