apiVersion: v1
kind: Secret
metadata:
    name: pantry-db-secret
    namespace: woodpantry
stringData:
    url: ENC[AES256_GCM,data:ZpQmpjg8oIagq5NXG19E9OszP9OdXpbUP+4XLieqpNsJN4qs/YfSRcmYSO5Xyc0llNG2cmjzfKeZn59V5rmVisdKNV2ioRZqDpR4hykw2ExzQBR6dRILJl7oOJRCH6IMCPKJWyKH+LJ9E+IrdNRjCS18qmMbwMZPvrMYR38gmyG+s2qT5A==,iv:Bd3rPJUR38jk8PtNGiBEhQPj9GB1Ttvg77aLKBugEUc=,tag:3xLXHbqeWVR5YYiQQ9fpNA==,type:str]
sops:
    age:
        - recipient: age1hkswjah635n6x22ftmm7m3dar0p9d2nk8pxzfnmpsthqr03hwvqsltsl6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNHJBbEZKMnRZY0p2c21D
            MitGaEVHMEVKM2dkUzE2dDdHRm8xWTZCRzJnClNmeTBOc2kwSVhmb2hBbC90MHkr
            OCtNOTczMjZORmwydGRQVGZ3NlRnbkUKLS0tIDNySkJZZitvWVlZcFJEOVp4OGYy
            aFBIakRtTkxCcktMLzQwOFdVc1ZUWEEK5IP1zsqreZGbNwrqrJZThDgImyQdEP/A
            F0YZ0hSv6TIfyoZL1pCcgiGyu/h7WF8OD2cizotuE1dsXQtkdF6L+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T00:51:07Z"
    mac: ENC[AES256_GCM,data:vJ5qC7tiMbkta540iYNzjUgavYTTVxbQ4FOnvfHXUa/SrL2GCeanA1B8IFlPETDNuD/ahmpSt5cC9pbMFvJssIUBKFrW+sGYqiA1mItTNVM3oP4pIHtesg45D6RtGBont5TpZnxjkCKpWnEYimgb7vYXQv21a+OQ7v3ytmJ58fw=,iv:RbENBF1Zw4BQd8IfpZm1e7E0vWDp9uvcAcdP/PYl43g=,tag:2pjaW/+OhA9gUJMn4aAvaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
