apiVersion: v1
kind: Secret
metadata:
    name: weather-alert-secrets
    namespace: weather-alert
type: Opaque
stringData:
    OPENWEATHER_API_KEY: ENC[AES256_GCM,data:bVmsiNalYVpoLvQb9etm,iv:3UjM+2KwxpZhFmiUZFKcdVgcjvey+Yll+YPeOk+PrB8=,tag:YiyGZwaae4sd/j+F/NPy6w==,type:str]
    NTFY_URL: ENC[AES256_GCM,data:OzEnPulWHkPgIre14ggifsXs9fpL7EgCgw==,iv:2a7nC8cazX2zE0CM9JIn5SvccImMBL/VXy1hU4TgCsQ=,tag:lIo3x0bOqvFt9bqGZ4EGDw==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:dpF4sRF96wEujMjsOnWEMNVo,iv:cvhoiyfpf3Ggb/ra4SnUQtoPML5QfGBYPJ/CmiGmuUk=,tag:Eu0vLOPPwmlU8QP6zx1Bvg==,type:str]
sops:
    age:
        - recipient: age1hkswjah635n6x22ftmm7m3dar0p9d2nk8pxzfnmpsthqr03hwvqsltsl6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N3psZU1zbCswa2VlbWZl
            azNpbGViOEpTU1FlS3BteExQL3dQSVBiempNCkpXTU5Nd3FDaUZTWCtTN1dxUWJJ
            aFNWK3g2TzFaYzVIdkg2YTUwakZqa28KLS0tIE9XUHlvVlB1dkRvaGhPR2JTSWI2
            QURQU1JPemZWRXZCV2toSTJDTlNZV1UKAH8nwU8XL1ox7K5qW5iwBZ5MoFU8jZWi
            LgRu/oC59gB8v6aX04+gJz9I0W0r4w67ImyfzwY+U8AmUjdnUlHRVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T00:10:09Z"
    mac: ENC[AES256_GCM,data:MLQlhCHBJrxNkmjzM8+izDs2PNeHTb22v1uYt1azo8yhP3VVnMIv35tJbfpVxqW1aMj7O4VAwV2FhYTLbk/RlsvQORBrN8dC26l50NhNh1BUF8vEPL1q+N6eeNTaK9rOMLJKQTwvqNMufo+1olN9MTVyqsaNI8PMyIykVjCr8h8=,iv:tS4N62mGu/iVRfzcrGEf+b9SpOLCfVReQRedor1dWvw=,tag:0gYGq4O4PEtWgz1RvNIsUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
