apiVersion: v1
kind: Secret
metadata:
    name: ingestion-secret
    namespace: woodpantry
stringData:
    rabbitmq_url: ENC[AES256_GCM,data:xCP+nPc4aaxxWoe0SbtN/R0WmE6U6EeRW3c9kIZbdUmXXM7bU5+jMygfuaasESPKo2diqoW9jxjLMpzRA0SiFgBf4N6d6YRaGL5h6Jy3/UnbN7+eyAnluVMe89k=,iv:Y79I7aof2SgkIjAITg8YVF9+C+e2E+sOrcNHk4hPy6E=,tag:HG8/rQKrMVI1XsuJiiwk6Q==,type:str]
sops:
    age:
        - recipient: age1hkswjah635n6x22ftmm7m3dar0p9d2nk8pxzfnmpsthqr03hwvqsltsl6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZENmcEtvNEk2SUh4UmVC
            cXdtVTVZOXEwdHBGNmhxVXVtMmtDS1JVVHhjCjlCTnMyNkdhTnJRa3ptWkdHQTFN
            bThqRjF6dklvazJCSUwxZUxNWmpZb28KLS0tIHAwVGxUR09XeDRhWDBIOEkvNTJR
            cTAvTzNhUHdsdzR0bDdCZi9saStrNW8KtkS3jqzRrj2kivq8PB5DfgJwN0DbPiUX
            IHqJ30MFGmQcLb7nmI6DoyX5NLq4ZXGQ+d8BFosxv8mXfZKIJaxuZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T23:41:47Z"
    mac: ENC[AES256_GCM,data:HPXOYZVP2lVKJhrO2GlhRtMvD8VbxhL7H0+MssXDY78bbSBad5KdRIuM3R2fvmc5hIE4Z60L58GAd/e7CjwX1n4B1/p0d35mm+T1a0mnH/IIKuPw0GrSSEHLTIo8XNjkxv10ll1BfJp/3dGfQDx1PFq+rAjz1ZGx/CKp1zVCYBE=,iv:cr7Iz+BatFnl4dYqwc5XP3sgXt3tDtwnVgQRuKv50sE=,tag:1cy5X9OjspPZwKHPbzl6KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
