apiVersion: v1
kind: Secret
metadata:
    name: twilio-secret
    namespace: woodpantry
type: Opaque
stringData:
    account_sid: ENC[AES256_GCM,data:McnRplcS/tsFNhppnFky+y70j0nynuWqlibtFR1u0Q==,iv:spP9+A+Fm4tWt7owTJBH3rMZehGK9wVbW9Gp97znynQ=,tag:5/IA8A4Yj7e57YG6zS7sfA==,type:str]
    auth_token: ENC[AES256_GCM,data:CpAZDqtAaFzWXfeyLYh3FQV1sdFj07dGqFpjcXa2,iv:75MjWAdtUtG4ltYx7ZJf92R/zmslUXTS8eklJXtusZM=,tag:EI8pw47G3k1tcxk52p5omA==,type:str]
    from_number: ENC[AES256_GCM,data:Y/5fJsDgDQLPgGhIiP8rVDn+/UIZClHyHsQ0QiDCIg==,iv:64BnI+j+ZEV2RDrxteezRI0DRuNSb8KYe7jaSjxSNzM=,tag:ue+RSG0o2RXemXJuhnxnXw==,type:str]
sops:
    age:
        - recipient: age1hkswjah635n6x22ftmm7m3dar0p9d2nk8pxzfnmpsthqr03hwvqsltsl6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc2o2RmJDOERVL0xocW00
            R3cyWUxmMkQ5ZTFlMmRaWThZcys1My9kSVNJCkpnTWxYMy9BODF4VHRUbk16NEVL
            N2hNNHdMOEl5OUtzaUhnMWs1MXQ0MlUKLS0tIHdVckgyTGpoM2dxNkFMMUxEcFBi
            YnJKcDE2UHU1Z0I4VExhQTFhQXl4MzQKDyY6qJqAP7URYEjTUPWsUzwsL6BSDTtM
            njWNcB6tEtqUw2CYOvV0nDcyU/Jz7ovhHZ46hF74PXO5hfYQ+x0Sng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:55:35Z"
    mac: ENC[AES256_GCM,data:jkRGSJDWytZfjtf6i/g1VuOIaNxd2dxSNLeYv2v9bUXhEDBGuPBgPRv3a0Y95bVkccZCO9ttwQRXyPTuzHUWAVZE4oSQ2/XMKNwp2lXP6N4ejmfasCtN8MWZB/i+Ajb+loGnP+13waSNNRXI2b8n11ZY8COMqyMXHieWX9ABG9k=,iv:QzAwx4HCy8PsfIvn06H66LTH3TKPr5nk3qu6O/c1zRQ=,tag:3MowyHTsjgmRGbixM5Vd3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
