apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: woodpantry-postgres
  namespace: woodpantry
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    storageClass: longhorn
    size: 5Gi

  monitoring:
    enablePodMonitor: false
