apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: woodpantry-matching
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/mwhite7112/woodpantry-matching
  ref:
    branch: main
