apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-issuers
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/cert-issuers
  prune: true
  wait: true
