apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: rabbitmq
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
