apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-credentials
    namespace: rabbitmq
type: Opaque
stringData:
    rabbitmq-password: ENC[AES256_GCM,data:8N/3w0eqPyzFlylM/06VzjHury48F+NdKLS+L1evZws=,iv:ycWtDliAUlapDNtQyjnb/Q11/I9/Y5mC84xwEVykQ+U=,tag:SWe+WZ8tlbOD3Lc6lZlFxQ==,type:str]
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:8iuYjMdsshDS5HG/n4c7RwyPwwb+o4YdyfTpXfcl+vo=,iv:tFhi6WLXu4COa4B1/FGldojSkqC+2x2SdeIXA+kxPkI=,tag:/bwjIdDcLrGNDi5WYoyKeg==,type:str]
sops:
    age:
        - recipient: age1hkswjah635n6x22ftmm7m3dar0p9d2nk8pxzfnmpsthqr03hwvqsltsl6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S3BBc0oxTVhzenZaZHBD
            ZzVUbDh3dmZrclYyUzBzOThlclhZWExZOWl3CjJSL3RLSkROTWZGZXQ0cWtjb2FB
            akI3WU5TaEF3ejM1YUovV1FpOVcwencKLS0tIDRLTjNNR0praHhhTG0rRzhKTUp0
            SGd0ZXJuWnozUUNPSml6a3JRTi9rbTgKNQQWHSUkEWP6tCYuaNYS7tWXjLp3LfU/
            wIF3rOxleioyXODC4f7NZa+jTkoqg4nCvE3enXCL/MaOiTfcXaAaHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T03:55:29Z"
    mac: ENC[AES256_GCM,data:KXeohoO574hZyf5EHqmuU0SRWAABg41+WEn3JbYmNhUtQkVfzAMWgoIaoEIXEHK3TQlvs7nToJQXrHYyNgl5WOn27V7qJ2ajAUUCP9Qo7yLiHkx2D2QHsFh86C8umXGVz318AF16G5avh3J8jpNZXf2mp4M19Wgkgq5Nhgb88w4=,iv:KtWFQtM1x5sNfqnVvivulfuPX5Ud1cjqzj9AU2GcFNo=,tag:CqcsN0iEEIoz9JGOD7s9Aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
