apiVersion: v1
kind: Secret
metadata:
    name: sops-test
    namespace: cluster-admin-sa
type: Opaque
stringData:
    test: ENC[AES256_GCM,data:55otNeUZ9ZgBwI98DNM5Z04BjPNhlytcRA==,iv:soJKJml/JpxfE+qTOOigDI6L/liVR3dUL+B6Lk0zJY0=,tag:ZaLJUZJi2OVfC7M1sdVUUA==,type:str]
sops:
    age:
        - recipient: age1hkswjah635n6x22ftmm7m3dar0p9d2nk8pxzfnmpsthqr03hwvqsltsl6e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSENtZ0N4bW1NQjN6Mmpq
            ZXp0UUVoL1I5SDRtRUhvQXZrZVNMcVVOOVM4CkVhNWN2MFJOUUErd2plL05VcEpJ
            S1lyVDVTOGt6Z1k3aG1QTFNGRGNqM28KLS0tIEpPTU4ydWRKQVBzemdVTk5jU0U4
            MHdkQ0hhMU1TdEpTK1A3ZzI4cUhiaDQK4UtKsUbD3xqQkJerJmE1/b6veZuUnHfc
            cMuU0kePqYwz0oRuX6vnDfS6nyL8DJ1axS5BLm5VDrAw2+8WdaxZ4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T07:06:01Z"
    mac: ENC[AES256_GCM,data:FsvvQzjQvcUMZIPOogI7Vh2fzwEPr/5RtOz2+IPGxJSKoxBJYJXvOGcDo4zc/1YalIw6XQUdYmQDj0eThFc0wcEE71bCjuXoXxYbXWQ6ZGXHf6bL2mY/0CiktrzfOupRqcr9sinXb8B+FR1jdGoXvFC1L433rjW0ccJH8Ayz0Ck=,iv:QK1vCSISIrZqc6y+kOzmKkNdQyRw/j4Gi/Q2/kumufg=,tag:mAAQ7uajmJZwMNDrKStcIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
